imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AppBundle/Resources/config/services.yml }

#    - { resource: @RVisDemoBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
#    paths:
#        "%kernel.root_dir%/../vendor/sonata-project/admin-bundle/Resources/views": foo_bar

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    templates:
        # search
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        # list: override of SonataAdminBundle:CRUD:list.html.twig
        list:                       AppBundle:Admin:list.html.twig
        action:                     SonataAdminBundle:CRUD:action.html.twig
        select:                     SonataAdminBundle:CRUD:list__select.html.twig
        list_block:                 SonataAdminBundle:Block:block_admin_list.html.twig
        short_object_description:   SonataAdminBundle:Helper:short-object-description.html.twig
        batch:                      SonataAdminBundle:CRUD:list__batch.html.twig
        inner_list_row:             SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:            SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:                SonataAdminBundle:Pager:links.html.twig
        pager_results:              SonataAdminBundle:Pager:results.html.twig
        # dashboard
        dashboard:                  SonataAdminBundle:Core:dashboard.html.twig
        # show
        show:                       SonataAdminBundle:CRUD:show.html.twig
        layout:                     AppBundle::standard_layout.html.twig
        # layout:                     SonataAdminBundle::standard_layout.html.twig
