AppBundle\Entity\Opdrachtgever:
    type: entity
    table: Opdrachtgever
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        opdrGeverCode:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: Opdr_gever_code
        naam:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: Naam
        adres:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: Adres
        postcode:
            type: string
            nullable: false
            length: 6
            fixed: false
            column: Postcode
        plaats:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: Plaats
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: Email
        internet:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'website van opdrachtgever op het internet'
            column: Internet
    lifecycleCallbacks: {  }
